import { defineConfig } from "@tanstack/react-start/config";

export default defineConfig({
	tsr: {
		appDirectory: "src",
		routeTreeFileHeader: [
			"/** biome-ignore-all lint/suspicious/noExplicitAny: code generated by @tanstack/react-start */",
		],
		quoteStyle: "double",
	},
});
